### ISSUE TITLE
plotFingerprint

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/snakemake_workflows#10]
plotFingerprint takes a long time with default -n 500000. Perhaps this parameter could be reduced? Please calculate also the metrics using --outQualityMetrics

**Comment by steffenheyne** [comment]
how to deal with "–JSDsample" in a multi-sample setup with multiple inputs? we need a call for each group of samples (chips + their input)? what is preferred?

**Comment by steffenheyne** [comment]
this now implemented in master, we select just the first available input for --JSDsample to get all the JS related metrics
