### ISSUE TITLE
Fix memory issue for "gigantic" genomes

### ISSUE THREAD

**Issue by mirax87** [maxplanck-ie/snakemake_workflows#23]
In order to count genes on very large genomes (e.g. hs with exons AND introns) there is a more than default memory required. 
In particular Salmon's suffix array construction (salmon index <genome.fa>) consumes a lot of memory. 
Add a parameter to the config file, to change SLURM --mem-per-cpu, if needed (default, stays with SLURM default).

**Comment by steffenheyne** [comment]
this is in master already, we introduced a cluster.yaml for the RNA-seq workflow and in there we can specify the memory requirements per tool. see to work for salmon with mouse now
