### ISSUE TITLE
Alternative downsampling method

### ISSUE THREAD

**Issue by mirax87** [maxplanck-ie/snakemake_workflows#26]
Currently, the DNA-seq pipeline downsamples by using the first N reads in a fastq file. Actual randomization can be achieved using _seqtk sample_ also for paired-end reads (_seqtk sample_ must be called for each Fastq seperately, and -s <seed> has to be identical for both Fastq files).

**Comment by steffenheyne** [comment]
the DNA-mapping pipeline is using already a properly randomized downsampling method. see shared/rules/FASTQ.snakefile line 42/55. the script "downsample_se_pe.sh" implements a reservoir sampling method for randomization.
