### ISSUE TITLE
Add multiQC

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakemake_workflows#31]
WIP...

**Comment by steffenheyne** [comment]
@vivekbhr this is now in develop...is it working?

**Comment by vivekbhr** [comment]
@steffenheyne yup.. The Issue would close automatically once develop is merge into master.

**Comment by steffenheyne** [comment]
ah ok

**Comment by vivekbhr** [comment]
It's in 0.6 release now
