### ISSUE TITLE
Retrospectively tag versions

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakemake_workflows#35]
only previous developers can do that. 

I am unaware of previous changes the workflow went through.. We should retrospectively tag the commits for versions (starting with v0.1). For example:

* v0.1 : first working implementation.
* v0.2 : addition of RNAseq
* v0.3 : scRNAseq

etc. etc..

Allele-specific workflow would then get it's own minor version number `(v 0.X.0)`...

**Comment by steffenheyne** [comment]
ok
better we tag also a version that is before allele-specifc, like current master that has a working version for all other workflows...

0.4 3da5acb1af34a5c91dcefa3929f1534f244a90db (Mon Sep 26 10:39:09 2016 +0200)
0.3 
0.0.1 f6c7c024656e4e160fd30e98bef86f48fe7ee570  (Thu Mar 24 09:53:11 2016 +0100)

**Comment by steffenheyne** [comment]
done till 0.4! 
versions under manke/repository/scripts/snakemake_workflows/ should match as best as possible
...we still have to decide what to tag as 0.5
