### ISSUE TITLE
picard MarkDuplicated and metrics file

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/snakemake_workflows#46]
the metrics file output from picard MarkDuplicates, reports the statistics only for "Unknown Library", although it should report per library = read group "@RG".
Read-group is defined during (bowtie) mapping, but does not seem to be recognized by MarkDuplicates. Does anyone know how to fix this? It's annoying because MultiQC will fail on those metrics files.

**Comment by steffenheyne** [comment]
there are some posts around that state that markDup is RG/lib aware. I don't know why this is not processed correctly right now. 

It seems that also the "LB" (library) field in  @RG needs to be set! Is this the case in your bams?
