### ISSUE TITLE
change the bamCompare output suffix

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakemake_workflows#47]
The suffix says `filtered.subtract.input.bw` and `filtered.log2ratio.over_input.bw` for the two bamCompare commands. But the `control` sample doesn't have to be INPUT. In my example I have both Input and H3 controls and If I re-run with H3 control the Input subtracted files would be either over-written or not produced.

**Comment by vivekbhr** [comment]
I would recommend adding `control Name` parameter in the yaml such that the output suffix says `filtered.log2ratio.over_<control_name>.bw`. This way users can specify different controls in the same yaml

**Comment by steffenheyne** [comment]
implemented in develop now
