### ISSUE TITLE
ChIP-Seq : keep only uniquely mapping reads by default

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakemake_workflows#48]
In the bam filtering rule, only uniquely mapping reads should be kept by default, we can specify a flag to count the multimappers if users wish to..

**Comment by vivekbhr** [comment]
We decided for now to change the documentation, recommending users to filter by mapq > 2 to avoind true uniquely mapping reads (i.e. without any mismatches)..

**Comment by steffenheyne** [comment]
this is now in develop
