### ISSUE TITLE
ChIP-Seq workflow, single-end option says TRUE by default

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakemake_workflows#57]
It actually represents the value for "paired" in the config.. It's confusing..

**Comment by steffenheyne** [comment]
fixed with `default=not(defaults["paired"]))`

**Comment by dpryan79** [comment]
It looks like this is still not actually working correctly.

**Comment by mirax87** [comment]
Unfortunately, I didnt properly mention it. 

Another project required me to perform PE and SE mode. I removed the `not` from `default=not(defaults["paired"]))`, which did the trick. I made it a PR #79

**Comment by dpryan79** [comment]
Merged and released.
