### ISSUE TITLE
Initial RTD migration

### ISSUE THREAD

**Issue by vivekbhr** [maxplanck-ie/snakemake_workflows#61]
We would move the existing index/help/readme content to RTD for now. Afterwards we can open a series of issues about documentation of each workflow separately..

**Comment by vivekbhr** [comment]
ok I tried to quickly build the docs by parsing the help messages but I am getting multiple errors from `sphinx-argparse` while trying to parse the wrapper files. Installing the scripts would solve these errors.. So I am giving up for now

**Comment by steffenheyne** [comment]
could this be solved in principal without installing?
How to setup sphinx correctly!? 

I did `sphinx-quickstart" and then added 
`extensions += ['sphinxarg.ext'] ` to conf.py
then I did `make html` ...but argparse didn't seem to run? How can I reproduce the problem?

**Comment by steffenheyne** [comment]
ah could we start with the deeptools/docs/conf.py ?

**Comment by vivekbhr** [comment]
I have done all that already on my local 'docs' branch.. let me push it and you can try to follow from there
